---

# Manage connections using Airflow CLI

- name: 'CONFIG | CONNECTIONS | Get existing connections'
  become_user: "{{ airflow_user_name }}"
  become: true
  shell: >
    set -o pipefail && \
      {{ airflow_virtualenv }}/bin/airflow connections list | grep -E "\s+'" | cut -d "'" -f2
  changed_when: false
  failed_when: False
  no_log: True
  register: 'airflow_existing_connections'
  args:
    executable: /bin/bash


# Only add and delete actions are managed, not update
- name: 'CONFIG | CONNECTIONS | Remove listed connections'
  command: >
    {{ airflow_virtualenv }}/bin/airflow connections delete --conn-id {{ item.conn_id }}
  changed_when: false
  no_log: True
  with_items: "{{ airflow_connections }}"
  when: 'item.conn_id in airflow_existing_connections.stdout_lines'


- name: 'CONFIG | CONNECTIONS | Add connections using conn_uri'
  command: >
    {{ airflow_virtualenv }}/bin/airflow connections add \
    --conn-id {{ item.conn_id }} \
    --conn-uri {{ item.conn_uri | default('') | quote }} \
    --conn-extra {{ item.conn_extra | default('') | quote }}
  changed_when: false
  no_log: True
  with_items: "{{ airflow_connections }}"
  when: "(item.conn_uri | default('')) | length > 0"


- name: 'CONFIG | CONNECTIONS | Add connections not using conn_uri with port'
  command: >
    {{ airflow_virtualenv }}/bin/airflow connections add \
    --conn-id {{ item.conn_id }} \
    --conn-type {{ item.conn_type | default('') | quote }} \
    --conn-host {{ item.conn_host | default('') | quote }} \
    --conn-login {{ item.conn_login | default('') | quote }} \
    --conn-password {{ item.conn_password | default('') | quote }} \
    --conn-schema {{ item.conn_schema | default('') | quote }} \
    --conn-extra {{ item.conn_extra | default('') | quote }}
  changed_when: false
  no_log: True
  with_items: "{{ airflow_connections }}"
  when:
    - "(item.conn_uri | default('')) | length == 0"
    - "(item.conn_port | default(0)) | int == 0"


- name: 'CONFIG | CONNECTIONS | Add connections not using conn_uri without port'
  command: >
    {{ airflow_virtualenv }}/bin/airflow connections add \
    --conn-id {{ item.conn_id }} \
    --conn-type {{ item.conn_type | default('') | quote }} \
    --conn-host {{ item.conn_host | default('') | quote }} \
    --conn-login {{ item.conn_login | default('') | quote }} \
    --conn-password {{ item.conn_password | default('') | quote }} \
    --conn-schema {{ item.conn_schema | default('') | quote }} \
    --conn-port {{ item.conn_port }} \
    --conn-extra {{ item.conn_extra | default('') | quote }}
  changed_when: false
  no_log: True
  with_items: "{{ airflow_connections }}"
  when:
    - "(item.conn_uri | default('')) | length == 0"
    - "(item.conn_port | default(0)) | int > 0"
